language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew build --scan -s
before_install:
  - rm -rf  $HOME/.gradle/caches
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
